### ISSUE TITLE
导出视频回调一直报错

### ISSUE THREAD

**Issue by SXDgit** [VictorZhang2014/TakeVideo#3]
一直报这个错，Error Domain=AVFoundationErrorDomain Code=-11822 "Cannot Open" UserInfo={NSLocalizedFailureReason=This media format is not supported., NSLocalizedDescription=Cannot Open, NSUnderlyingError=0x109446480 {Error Domain=NSOSStatusErrorDomain Code=-16976 "(null)"}}

找不到原因

**Comment by VictorZhang2014** [comment]
你能描述下，你在什么环境下遇到的这个问题吗？比如xcode版本，iOS模拟器还是真机
